arike/home/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from arike.home.views import (
    ActivateAccountView,
    DashboardView,
    UserLoginView,
    UserProfileWithPasswordChangeView,
)

app_name = "home"

urlpatterns = [
    path("", DashboardView.as_view(), name="home_dashboard"),
    path("login", UserLoginView.as_view(), name="login_user"),
    path("logout", LogoutView.as_view(), name="logout_user"),
    path("account/<pk>", UserProfileWithPasswordChangeView.as_view(), name="user_profile"),
    path("account/activate/<uidb64>/<token>/", ActivateAccountView.as_view(), name="activate_account"),
]

arike/patients/urls.py
from django.urls import path

from arike.patients.views import (
    PatientCreateView,
    PatientDetailView,
    PatientFamilyCreateView,
    PatientFamilyDeleteView,
    PatientFamilyListView,
    PatientFamilyUpdateView,
    PatientVisitHistoryDetailView,
    PatientVisitHistoryView,
    PatientsListView,
    PatientUpdateView,
)

app_name = "patients"

urlpatterns = [
    path('', PatientsListView.as_view(), name='patients_list'),
    path('create', PatientCreateView.as_view(), name='patient_create'),
    path('<pk>', PatientDetailView.as_view(), name='patient_detail'),
    path('update/<pk>', PatientUpdateView.as_view(), name='patient_update'),
    path('<int:uid>/family', PatientFamilyListView.as_view(), name='patient_family_list'),
    path('<int:uid>/family/create', PatientFamilyCreateView.as_view(), name='patient_family_create'),
    path('<int:uid>/family/delete/<pk>', PatientFamilyDeleteView.as_view(), name='patient_family_detail'),
    path('<int:uid>/family/update/<pk>', PatientFamilyUpdateView.as_view(), name='patient_family_update'),
    path('<int:uid>/visit/history', PatientVisitHistoryView.as_view(), name="patient_visit_history"),
    path('<int:uid>/visit/detail/<pk>', PatientVisitHistoryDetailView.as_view(), name="patient_visit_history_detail")
]

arike/treatments/urls.py
from django.urls import path

from arike.treatments.views import (
    DiseaseHistoryCreateView,
    DiseaseHistoryDeleteView,
    DiseaseHistoryListView,
    DiseaseHistoryUpdateView,
    TreatmentCreateView,
    TreatmentDeleteView,
    TreatmentListView,
    TreatmentUpdateView,
    load_treatment_care_sub_type,
)

app_name = "treatments"

urlpatterns = [
    path("<int:uid>/disease/history", DiseaseHistoryListView.as_view(), name="disease_history_list"),
    path("<int:uid>/disease/history/create", DiseaseHistoryCreateView.as_view(), name="disease_history_create"),
    path("<int:uid>/disease/history/update/<pk>", DiseaseHistoryUpdateView.as_view(), name="disease_history_update"),
    path("<int:uid>/disease/history/delete/<pk>", DiseaseHistoryDeleteView.as_view(), name="disease_history_delete"),

    path("<int:uid>/disease/treatments", TreatmentListView.as_view(), name="treatment_list"),
    path("<int:uid>/disease/treatments/create", TreatmentCreateView.as_view(), name="treatment_create"),
    path("<int:uid>/disease/treatments/update/<pk>", TreatmentUpdateView.as_view(), name="treatment_update"),
    path("<int:uid>/disease/treatments/delete/<pk>", TreatmentDeleteView.as_view(), name="treatment_delete"),

    path("load/care_sub_types/", load_treatment_care_sub_type, name="load_care_sub_types"),
]

arike/users/urls.py
from django.urls import path

from arike.users.views import (
    GenericUserAssignView,
    GenericUserCreateView,
    GenericUserDeleteView,
    GenericUserDetailView,
    GenericUserUpdateAssignView,
    GenericUserUpdateView,
    GenericUsersView,
)

app_name = "users"
urlpatterns = [
    path("", GenericUsersView.as_view(), name="users_list"),
    path("create", GenericUserCreateView.as_view(), name="create_user"),
    path("<pk>", GenericUserDetailView.as_view(), name="detail_user"),
    path("update/<pk>", GenericUserUpdateView.as_view(), name="update_user"),
    path("delete/<pk>", GenericUserDeleteView.as_view(), name="delete_user"),
    path("create/<int:uid>/assign", GenericUserAssignView.as_view(), name="assign_facility"),
    path("update/<int:uid>/assign", GenericUserUpdateAssignView.as_view(), name="update_assigned_facility"),
]

arike/visits/urls.py
from django.urls import path

from arike.visits.views import (
    ActiveTreatmentsView,
    CreatePatientHealthInfoView,
    CreateTreatmentNoteView,
    ScheduleVisitView,
    SchedulesView,
    TreatmentDetailView,
    UpcomingVisitsView,
    VisitView,
    unschedule_visit,
)

app_name = "visits"

urlpatterns = [
    path("", SchedulesView.as_view(), name="schedules"),
    path("upcoming", UpcomingVisitsView.as_view(), name="upcoming_visits"),
    path("<int:uid>/schedule", ScheduleVisitView.as_view(), name="schedule_visit"),
    path("<int:uid>/visit/<int:vid>", VisitView.as_view(), name="visit"),
    path("<int:uid>/visit/<int:vid>/delete", unschedule_visit, name="unschedule_visit"),
    path("<int:uid>/visit/<int:vid>/health-info", CreatePatientHealthInfoView.as_view(), name="create_patient_health_info"),
    path("<int:uid>/visit/<int:vid>/treatments", ActiveTreatmentsView.as_view(), name="treatment_note"),
    path("<int:uid>/visit/<int:vid>/treatments/<pk>", TreatmentDetailView.as_view(), name="treatment_details"),
    path("<int:uid>/visit/<int:vid>/treatments/<int:tid>/note", CreateTreatmentNoteView.as_view(), name="create_treatment_note"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path("users/", include("arike.users.urls", namespace="users")),
    path("facilities/", include("arike.facilities.urls", namespace="facilities")),
    path('patients/', include('patients.urls', namespace="patients")),
    path('patients/', include('treatments.urls', namespace='treatments')),
    path('visits/', include('visits.urls', namespace='visits')),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

arike/patients/models.py
from datetime import date, datetime

from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db import models

from arike.facilities.models import Facility, Ward

GENDER_CHOICE = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Other', 'Other')
)

RELATION_CHOICE = (
    ('1', 'Father'),
    ('2', 'Mother'),
    ('3', 'Son'),
    ('4', 'Sister'),
    ('5', 'GrandFather'),
    ('6', 'GrandMother'),
    ('7', 'Uncle'),
    ('8', 'Aunt'),
    ('9', 'Others'),
)

EDUCATION_CHOICE = (
    ('1', '10th Passed'),
    ('2', '12th Passed'),
    ('3', 'Graduation'),
    ('4', 'Post Graduation'),
    ('5', 'PhD'),
    ('6', 'Illiterate'),
    ('7', 'Others'),
)

class Patient(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150, blank=True)
    email = models.EmailField()
    gender = models.CharField(max_length=10, choices=GENDER_CHOICE, default=GENDER_CHOICE[0][0])
    birth_date = models.DateField(null=True)
    phone_number = models.CharField(max_length=14)
    address = models.CharField(max_length=200)
    landmark = models.CharField(max_length=200)
    emergency_phone_number = models.CharField(max_length=14, null=True)
    expired_time = models.DateTimeField(null=True)
    ward = models.ForeignKey(Ward, on_delete=models.CASCADE, null=True)
    facility = models.ForeignKey(Facility, on_delete=models.CASCADE) 
    deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def is_expired(self):
        return self.expired_time <= datetime.now()

    def age(self):
        today = date.today()
        age = today.year - self.birth_date.year - ((today.month, today.day) < (self.birth_date.month, self.birth_date.day))
        return age


class PatientFamily(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150, blank=True)
    email = models.EmailField()
    birth_date = models.DateField(null=True)
    phone_number = models.CharField(max_length=14)
    relation = models.CharField(max_length=50, choices=RELATION_CHOICE, default=RELATION_CHOICE[0][0])
    education = models.CharField(max_length=50, choices=EDUCATION_CHOICE, default=EDUCATION_CHOICE[0][0])
    occupation = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    remarks = models.CharField(max_length=200, blank=True)
    is_primary = models.BooleanField(default=False)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICE, default=GENDER_CHOICE[0][0])
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
    def age(self):
        today = date.today()
        age = today.year - self.birth_date.year - ((today.month, today.day) < (self.birth_date.month, self.birth_date.day))
        return age

arike/facilities/forms.py
from django import forms
from arike.facilities.models import Facility

class FacilityCreateForm(forms.ModelForm):

    class Meta:
        model = Facility
        fields = ['kind', 'name', 'address', 'ward', 'pin_code', 'phone_number']

    def clean_name(self):
        data = self.cleaned_data['name']
        if data is None:
            self.add_error('name', 'Name is required')
        return data 

    def clean_pin_code(self):
        data = self.cleaned_data['pin_code']
        if data is None:
            self.add_error('pin_code', 'Pin code is required')
        return data 
    

arike/home/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.forms import ValidationError
from django.utils.translation import gettext_lazy as _


User = get_user_model()


class SetPasswordForm(forms.ModelForm):
    error_messages = {
        'password_mismatch': _('The two password fields didn’t match.'),
    }
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
    )

    class Meta:
        model = User
        fields = ['new_password1', 'new_password2']
    
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(SetPasswordForm, self).__init__(*args, **kwargs)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        password_validation.validate_password(password2, self.user)
        return password2

arike/facilities/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from arike.facilities.filters import FacilityFilter

from arike.facilities.forms import FacilityCreateForm
from arike.facilities.models import Facility


class AuthorisedFacilityManager(LoginRequiredMixin, PermissionRequiredMixin):

    def get_queryset(self):
        return Facility.objects.filter(deleted=False)
    
class GenericFacilitiesView(LoginRequiredMixin, ListView):
    template_name = "facilities/facilities.html"
    context_object_name = "facilities"

    def get_queryset(self):
        return Facility.objects.filter(deleted=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = FacilityFilter(self.request.GET, queryset=self.get_queryset())
        return context 

class GenericFacilityCreateView(AuthorisedFacilityManager, CreateView):
    permission_required = "facilities.add_facility"
    form_class = FacilityCreateForm
    template_name = "facilities/create_facility.html"
    success_url = "/facilities/"

class GenericFacilityUpdateView(AuthorisedFacilityManager, UpdateView):
    permission_required = "facilities.change_facility"
    model = Facility
    form_class = FacilityCreateForm
    template_name = "facilities/update_facility.html"
    success_url = "/facilities/"

class GenericFacilityDetailView(LoginRequiredMixin, DetailView):
    model = Facility
    template_name = "facilities/detail_facility.html"

class GenericFacilityDeleteView(AuthorisedFacilityManager, DeleteView):
    permission_required = "facilities.delete_facility"
    model = Facility
    template_name = "facilities/delete_facility.html"
    success_url = "/facilities/"

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        Facility.objects.filter(pk=self.object.pk).update(deleted=True)
        return HttpResponseRedirect(self.get_success_url())

arike/home/views.py
from django.contrib.auth import forms as auth_forms
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.http import (
    HttpResponse,
    HttpResponseForbidden,
    HttpResponseNotAllowed,
    HttpResponsePermanentRedirect,
)
from arike.users.token import account_activation_token
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView

from arike.home.forms import SetPasswordForm

User = get_user_model()
class UserLoginView(LoginView):
    template_name = 'users/user_login.html'

class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "home/dashboard.html"

class UserProfileWithPasswordChangeView(PasswordChangeView):
    form_class = auth_forms.SetPasswordForm
    template_name = 'home/user_profile.html'
    success_url = '/users'

    def get(self, request, *args, **kwargs):
        user = User.objects.get(pk=kwargs['pk'])
        if self.request.user.id != user.id or user.is_active == False:
            return HttpResponseForbidden("You are not allowed to access this page")

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'] = User.objects.get(pk=self.kwargs['pk'])
        return context

class ActivateAccountView(UpdateView):
    form_class = SetPasswordForm
    template_name = 'home/user_verify_update.html'
    success_url = '/login'

    def get(self, request, *args, **kwargs):
        uidb64 = kwargs['uidb64']
        token = kwargs['token']
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None 
        if user is not None and account_activation_token.check_token(user, token):
            return super().get(request, *args, **kwargs)
        else:
            return HttpResponse("Activation link is invalid!")
    
    def get_object(self):
        uid = force_text(urlsafe_base64_decode(self.kwargs['uidb64']))
        user = User.objects.get(pk=uid)
        return user 
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.object
        return kwargs

    def form_valid(self, form):
        # Set the new password
        password = form.cleaned_data['new_password1']
        self.object.set_password(password)
        self.object.is_verified = True
        self.object.save()

        return HttpResponsePermanentRedirect(self.get_success_url())

arike/templates/patients/detail_patient.html
{% extends 'base.html' %}
{% block title %} Patients {% endblock %}

{% block content %}
    {% include 'components/sidenav.html' %}
    <div class="ml-[320px] bg-primary_bg min-h-screen px-12 py-8">
        <h2 class="text-3xl text-primary_color font-extrabold">{{ object }}</h2>

        <div class="flex flex-row items-center justify-between mt-12">
            <h3 class="text-2xl text-primary_color font-bold">Personal Information</h3>
            {% include 'components/buttons/contained_small.html' with url_namespace='patients:patient_update' pk=object.id text='Edit' %}
        </div>

        <div class="flex flex-row justify-between my-8">
            <div class="bg-white rounded-2xl px-8 py-4 w-[calc(100%-25rem)] min-h-[320px] flex flex-col justify-center">
                <h3 class="text-lg font-bold text-primary_color">{{ object }}</h3>
                <p class="text-[15px] text-grey_light font-medium">{{ object.address }}</p>
                <div class="flex flex-row pt-4 justify-between">
                    <div class="">
                        <h4 class="text-[15px] text-grey_dark font-bold">Phone Number</h4>
                        <span class="text-[15px] text-link_color font-medium">{{ object.phone_number }}</span>

                        <h4 class="text-[15px] text-grey_dark font-bold mt-2">Gender</h4>
                        <span class="text-[15px] text-primary_color">{{ object.gender }}</span>

                        <h4 class="text-[15px] text-grey_dark font-bold mt-2">Last Visit</h4>
                        <span class="text-[15px] text-primary_color">{{ last_visit }}</span>
                    </div>
                    <div class="">
                        <h4 class="text-[15px] text-grey_dark font-bold">Emergency Phone Number</h4>
                        <span class="text-[15px] text-link_color font-medium">{{ object.emergency_phone_number|default:'Not given' }}</span>

                        <h4 class="text-[15px] text-grey_dark font-bold mt-2">Facility</h4>
                        <span class="text-[15px] text-primary_color">{{ object.facility }}</span>

                        <h4 class="text-[15px] text-grey_dark font-bold mt-2">Next Visit</h4>
                        <span class="text-[15px] text-primary_color">{{ next_visit }}</span>
                    </div>
                </div>
            </div>
            <div class="flex flex-col justify-between">
                <a href="{% url 'patients:patient_visit_history' uid=object.pk %}" class="text-2xl text-primary_color bg-white font-bold rounded-2xl py-14 px-20 justify-between text-center">Visits</a>
                <a href="{% url 'treatments:treatment_list' uid=object.pk %}" class="text-2xl text-primary_color bg-white font-bold rounded-2xl py-14 px-20 justify-between">Treatments</a>
            </div>
        </div>
        <div class="w-[calc(100%-25rem)] flex flex-row justify-between">
            <a href="{% url 'patients:patient_family_list' uid=object.pk %}" class="text-2xl text-primary_color bg-white font-bold rounded-2xl py-14 px-20 justify-between text-center">Family Details</a>
            <a href="{% url 'treatments:disease_history_list' uid=object.pk %}" class="text-2xl text-primary_color bg-white font-bold rounded-2xl py-14 px-20 justify-between">Disease History</a>
        </div>
    </div>
{% endblock %}

arike/templates/patients/patient_family.html
{% extends 'base.html' %}
{% block title %} Patient Family {% endblock %}

{% block content %}
    {% include 'components/sidenav.html' %}
    <div class="ml-[320px] bg-primary_bg min-h-screen px-16">
        {% include 'components/list_header.html' with header='Family Details' url_namespace='patients:patient_family_create' uid=view.kwargs.uid permission=perms.patients.add_patientfamily %}
        
        <h2 class="text-2xl font-bold text-primary_color mt-12">{{ patient }}</h2>
        <p class="text-lg text-grey_dark">{{ patient.address }}</p>

        <div class="flex flex-row flex-wrap items-center mt-4 justify-between">
            {% for member in patient_families %}
                <div class="flex flex-col min-w-[440px] w-[45%] py-5 px-4 bg-white rounded-2xl my-6">
                    <div class="flex flex-row justify-between">
                        <h3 class="text-xl font-bold text-primary_color">{{ member }}</h3>
                        <span class="text-[15px] text-grey_dark font-semibold pr-5">{{ member.get_relation_display }}</span>
                    </div>
                    <p class="mt-2 text-[15px] text-grey_dark">{{ member.address }}</p>
                    <div class="flex flex-row mt-3">
                        <div class="w-1/2">
                            <p class="text-[15px] text-link_color font-semibold">{{ member.phone_number }}</p>
                            <p class="text-[15px] text-grey_dark font-bold mt-2">Birth Date</p>
                            <p class="text-[15px] text-primary_color">{{member.birth_date }} ({{member.age}} years)</p>
                            <p class="text-[15px] text-grey_dark font-bold mt-2">Education</p>
                            <p class="text-[15px] text-primary_color">{{ member.get_education_display }}</p>
                        </div>
                        <div class="w-1/2">
                            <p class="text-[15px] text-link_color font-semibold">{{ member.email }}</p>
                            <p class="text-[15px] text-grey_dark font-bold mt-2">Occupation</p>
                            <p class="text-[15px] text-primary_color">{{ member.occupation|default:'Not provided' }}</p>
                            <p class="text-[15px] text-grey_dark font-bold mt-2">Remarks</p>
                            <p class="text-[15px] text-primary_color">{{ member.remarks|default:'No remarks' }}</p>
                        </div>
                    </div>
                    <div class="flex flex-row mt-4">
                        <a href="/patients/{{ view.kwargs.uid }}/family/delete/{{ member.id }}" class="bg-white text-primary_color border-2 border-primary_color rounded-lg text-sm font-semibold px-7 py-2">Delete</a>
                        <a href="/patients/{{ view.kwargs.uid }}/family/update/{{ member.id }}" class="ml-3 bg-primary_color text-white border-2 border-primary_color rounded-lg text-sm font-semibold px-7 py-2">Edit</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

arike/templates/patients/patients.html
{% extends 'base.html' %}
{% load facility_extras %} 
{% load users_extras %}

{% block title %} Patients {% endblock %}

{% block styling %}
<style>
    #collapsible_btn:after {
        content: '\02795';
        font-size: 15px;
        color: white;
        float: right;
        margin-left: 8px;
    }
    .active_button {
        background-color: #e4e4e4;
        border-bottom-left-radius: 0;
        border-bottom-right-radius: 0;
    }
    .active_button#collapsible_btn:after {
        content: "\2796";
    }
    .active_form {
        border-top-left-radius: 0;
        border-top-right-radius: 0;
        padding-bottom: 2rem;
    }
</style>
{% endblock %}

{% block content %}
    {% include 'components/sidenav.html' %}
    <div class="ml-[320px] bg-primary_bg min-h-screen">
        <div class="max-w-[1000px] w-full mx-auto">
            {% include 'components/list_header.html' with header='Patients' url_namespace='patients:patient_create' uid='' permission=perms.patients.add_patient %}

            <button type="button" id="collapsible_btn" class="max-w-[700px] w-full py-4 px-6 rounded-xl bg-white text-left text-xl font-extrabold text-primary_color border-0 outline-0 cursor-pointer hover:bg-[#e4e4e4]">Apply Filters</button>
                <form method="get" id="collapsible_form" class="overflow-hidden max-w-[700px] w-full px-6 bg-white rounded-bl-xl rounded-br-xl max-h-0 transition-all ease-out delay-200">
                    <div class="flex flex-row flex-wrap gap-5 py-5">
                        <div class="w-full my-2">
                            <label for="id_search" class="absolute p-0 border-0 h-px w-px overflow-hidden">Search patients</label>
                            <input 
                                type="text"  
                                id="id_search" 
                                name="search" 
                                {% if request.GET.search %} value="{{ request.GET.search }}" {% endif %}
                                placeholder="Search patients"
                                class="min-w-60 w-1/2 h-12 rounded-xl px-4 border-2 outline-0 text-[16px] focus:ring-0"
                            >
                        </div>
                        <select name="{{filter.form.ward.html_name}}" id="{{filter.form.ward.auto_id}}" class="max-w-[200px] w-4/12 h-12 border-2 rounded-lg bg-white pl-5 focus:ring-0">
                            <option value="" disabled selected class="pl-4 text-[#6E7191]">Ward</option>
                            {% for x, y in filter.form.fields.ward.choices %} 
                                <option value="{{ x }}" {% if filter.form.ward.value == x|slugify %} selected {% endif %}>{{ y }}</option>
                            {% endfor %}
                        </select>
        
                        <select name="{{filter.form.facility.html_name}}" id="{{filter.form.facility.auto_id}}" class="max-w-[200px] w-4/12 h-12 border-2 rounded-lg bg-white pl-5 focus:ring-0">
                            <option value="" disabled selected class="pl-4 text-[#6E7191]">Facility</option>
                            {% for x, y in filter.form.fields.facility.choices %} 
                                <option value="{{ x }}" {% if filter.form.facility.value == x|slugify %} selected {% endif %}>{{ y }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button 
                        type="submit" 
                        class="w-28 py-3 rounded-[12px] bg-primary_color text-[16px] font-semibold text-white tracking-wider"
                    >
                        Apply
                    </button>
                </form>
                <div class="flex gap-4 mt-8">
                    {% with wardId=request.GET.ward facilityId=request.GET.facility search=request.GET.search %}
                        {% if wardId %}<div class="text-sm py-1 px-6 bg-primary_color text-white rounded-lg">Ward "{{ wardId|ward_name }}"</div>{% endif %}
                        {% if facilityId %}<div class="text-sm py-1 px-6 bg-primary_color text-white rounded-lg">{{ facilityId|get_facility }}</div>{% endif %}
                        {% if search %}<div class="text-sm py-1 px-6 bg-primary_color text-white rounded-lg">Search "{{ search }}"</div>{% endif %}
                    {% endwith %}
                </div>
            
            <div class="flex flex-row flex-wrap items-center">
                {% for patient in filter.qs %}
                    {% include 'patients/patient_card.html' with patient=patient %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}


{% block scripts %} 
<script>
    const collapsible_btn = document.getElementById("collapsible_btn");
    
    collapsible_btn.addEventListener("click", () => {
        const collapsible_form = document.getElementById("collapsible_form");
        collapsible_form.classList.toggle("active_form");
        collapsible_btn.classList.toggle("active_button");

        if(collapsible_form.style.maxHeight) {
            collapsible_form.style.maxHeight = null;
        } else {
            collapsible_form.style.maxHeight = `calc(${collapsible_form.scrollHeight}px + 2rem)`;
        }
    })
</script>
{% endblock %}