arike/home/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from arike.home.views import (
    ActivateAccountView,
    DashboardView,
    UserLoginView,
    UserProfileWithPasswordChangeView,
)

app_name = "home"

urlpatterns = [
    path("", DashboardView.as_view(), name="home_dashboard"),
    path("login", UserLoginView.as_view(), name="login_user"),
    path("logout", LogoutView.as_view(), name="logout_user"),
    path("account/<pk>", UserProfileWithPasswordChangeView.as_view(), name="user_profile"),
    path("account/activate/<uidb64>/<token>/", ActivateAccountView.as_view(), name="activate_account"),
]

arike/treatments/urls.py
from django.urls import path

from arike.treatments.views import (
    DiseaseHistoryCreateView,
    DiseaseHistoryDeleteView,
    DiseaseHistoryListView,
    DiseaseHistoryUpdateView,
    TreatmentCreateView,
    TreatmentDeleteView,
    TreatmentListView,
    TreatmentUpdateView,
    load_treatment_care_sub_type,
)

app_name = "treatments"

urlpatterns = [
    path("<int:uid>/disease/history", DiseaseHistoryListView.as_view(), name="disease_history_list"),
    path("<int:uid>/disease/history/create", DiseaseHistoryCreateView.as_view(), name="disease_history_create"),
    path("<int:uid>/disease/history/update/<pk>", DiseaseHistoryUpdateView.as_view(), name="disease_history_update"),
    path("<int:uid>/disease/history/delete/<pk>", DiseaseHistoryDeleteView.as_view(), name="disease_history_delete"),

    path("<int:uid>/disease/treatments", TreatmentListView.as_view(), name="treatment_list"),
    path("<int:uid>/disease/treatments/create", TreatmentCreateView.as_view(), name="treatment_create"),
    path("<int:uid>/disease/treatments/update/<pk>", TreatmentUpdateView.as_view(), name="treatment_update"),
    path("<int:uid>/disease/treatments/delete/<pk>", TreatmentDeleteView.as_view(), name="treatment_delete"),

    path("load/care_sub_types/", load_treatment_care_sub_type, name="load_care_sub_types"),
]

arike/users/urls.py
from django.urls import path

from arike.users.views import (
    GenericUserAssignView,
    GenericUserCreateView,
    GenericUserDeleteView,
    GenericUserDetailView,
    GenericUserUpdateAssignView,
    GenericUserUpdateView,
    GenericUsersView,
)

app_name = "users"
urlpatterns = [
    path("", GenericUsersView.as_view(), name="users_list"),
    path("create", GenericUserCreateView.as_view(), name="create_user"),
    path("<pk>", GenericUserDetailView.as_view(), name="detail_user"),
    path("update/<pk>", GenericUserUpdateView.as_view(), name="update_user"),
    path("delete/<pk>", GenericUserDeleteView.as_view(), name="delete_user"),
    path("create/<int:uid>/assign", GenericUserAssignView.as_view(), name="assign_facility"),
    path("update/<int:uid>/assign", GenericUserUpdateAssignView.as_view(), name="update_assigned_facility"),
]

arike/visits/urls.py
from django.urls import path

from arike.visits.views import (
    ActiveTreatmentsView,
    CreatePatientHealthInfoView,
    CreateTreatmentNoteView,
    ScheduleVisitView,
    SchedulesView,
    TreatmentDetailView,
    UpcomingVisitsView,
    VisitView,
    unschedule_visit,
)

app_name = "visits"

urlpatterns = [
    path("", SchedulesView.as_view(), name="schedules"),
    path("upcoming", UpcomingVisitsView.as_view(), name="upcoming_visits"),
    path("<int:uid>/schedule", ScheduleVisitView.as_view(), name="schedule_visit"),
    path("<int:uid>/visit/<int:vid>", VisitView.as_view(), name="visit"),
    path("<int:uid>/visit/<int:vid>/delete", unschedule_visit, name="unschedule_visit"),
    path("<int:uid>/visit/<int:vid>/health-info", CreatePatientHealthInfoView.as_view(), name="create_patient_health_info"),
    path("<int:uid>/visit/<int:vid>/treatments", ActiveTreatmentsView.as_view(), name="treatment_note"),
    path("<int:uid>/visit/<int:vid>/treatments/<pk>", TreatmentDetailView.as_view(), name="treatment_details"),
    path("<int:uid>/visit/<int:vid>/treatments/<int:tid>/note", CreateTreatmentNoteView.as_view(), name="create_treatment_note"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path("users/", include("arike.users.urls", namespace="users")),
    path("facilities/", include("arike.facilities.urls", namespace="facilities")),
    path('patients/', include('patients.urls', namespace="patients")),
    path('patients/', include('treatments.urls', namespace='treatments')),
    path('visits/', include('visits.urls', namespace='visits')),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

arike/treatments/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth import get_user_model
from arike.patients.models import Patient
from arike.visits.models import User, VisitDetail

User = get_user_model()

class Disease(models.Model):
    name = models.CharField(max_length=100)
    icds_code = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name 

class CareType(models.Model):
    name = models.CharField(max_length=100) 

    def __str__(self):
        return self.name

class CareSubType(models.Model):
    name = models.CharField(max_length=200)
    care_type = models.ForeignKey(CareType, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Treatment(models.Model):
    care_type = models.ForeignKey(CareType, on_delete=models.CASCADE)
    care_sub_type = models.ForeignKey(CareSubType, on_delete=models.CASCADE)
    description = models.CharField(max_length=300)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    given_by = models.ForeignKey(User, on_delete=models.CASCADE)
    deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def pretty_created_date(self):
        return self.created_at.strftime("%d %b %Y")
    
    def pretty_updated_date(self):
        return self.updated_at.strftime("%d %b %Y")

class TreatmentNote(models.Model):
    note = models.CharField(max_length=200)
    description = models.CharField(max_length=300, null=True, blank=True)
    treatment = models.ForeignKey(Treatment, on_delete=models.CASCADE)
    visit_details = models.ForeignKey(VisitDetail, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.note

    def pretty_created_date(self):
        return self.created_at.strftime("%d %b %Y")

class PatientDisease(models.Model):
    remarks = models.CharField(max_length=200, blank=True)
    disease = models.ForeignKey(Disease, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    treatment = models.ForeignKey(Treatment, on_delete=models.CASCADE, blank=True, null=True)
    investigated_by = models.ForeignKey(User, on_delete=models.CASCADE)
    deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def pretty_updated(self):
        return self.updated_at.strftime("%d %b %Y")

arike/facilities/forms.py
from django import forms
from arike.facilities.models import Facility

class FacilityCreateForm(forms.ModelForm):

    class Meta:
        model = Facility
        fields = ['kind', 'name', 'address', 'ward', 'pin_code', 'phone_number']

    def clean_name(self):
        data = self.cleaned_data['name']
        if data is None:
            self.add_error('name', 'Name is required')
        return data 

    def clean_pin_code(self):
        data = self.cleaned_data['pin_code']
        if data is None:
            self.add_error('pin_code', 'Pin code is required')
        return data 
    

arike/home/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.forms import ValidationError
from django.utils.translation import gettext_lazy as _


User = get_user_model()


class SetPasswordForm(forms.ModelForm):
    error_messages = {
        'password_mismatch': _('The two password fields didn’t match.'),
    }
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
    )

    class Meta:
        model = User
        fields = ['new_password1', 'new_password2']
    
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(SetPasswordForm, self).__init__(*args, **kwargs)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        password_validation.validate_password(password2, self.user)
        return password2

arike/patients/forms.py
from django.forms import ModelForm
from arike.patients.models import Patient, PatientFamily

class PatientCreationForm(ModelForm):

    class Meta:
        model = Patient
        fields = ['first_name', 'last_name', 'email', 'birth_date', 'phone_number', 'emergency_phone_number', 'address', 'ward', 'facility', 'gender']
    
    def __init__(self, *args, **kwargs):
        super(PatientCreationForm, self).__init__(*args, **kwargs)
        self.fields['last_name'].required = False 
        self.fields['emergency_phone_number'].required = False

class PatientFamilyCreationForm(ModelForm):

    class Meta:
        model = PatientFamily
        fields = "__all__"
        exclude = ['occupation', 'remarks', 'is_primary', 'patient', 'deleted']

arike/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.forms import ModelChoiceField, ModelForm
from django.utils.translation import gettext_lazy as _

from arike.home.models import District

User = get_user_model()


class UserCreateForm(ModelForm):

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email", "district"]
    
    def clean_first_name(self):
        data = self.cleaned_data["first_name"]
        if len(data) < 2:
            self.add_error("first_name", "First name must be at least 2 characters long")
        return data
    
    def clean_email(self):
        data = self.cleaned_data["email"]
        if not data:
            self.add_error("email", "Email is required")
        return data
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["district"] = ModelChoiceField(queryset=District.objects.all(), empty_label=None)

class UserFacilityAssignForm(ModelForm):

    class Meta:
        model = User 
        fields = ["facility", "role"]

    def clean_facility(self):
        data = self.cleaned_data["facility"]
        if not data:
            self.add_error("facility", "Facility is required")
        return data

    def clean_role(self):
        data = self.cleaned_data["role"]
        if not data or data == "none":
            self.add_error("role", "Role is required")
        return data

arike/facilities/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from arike.facilities.filters import FacilityFilter

from arike.facilities.forms import FacilityCreateForm
from arike.facilities.models import Facility


class AuthorisedFacilityManager(LoginRequiredMixin, PermissionRequiredMixin):

    def get_queryset(self):
        return Facility.objects.filter(deleted=False)
    
class GenericFacilitiesView(LoginRequiredMixin, ListView):
    template_name = "facilities/facilities.html"
    context_object_name = "facilities"

    def get_queryset(self):
        return Facility.objects.filter(deleted=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = FacilityFilter(self.request.GET, queryset=self.get_queryset())
        return context 

class GenericFacilityCreateView(AuthorisedFacilityManager, CreateView):
    permission_required = "facilities.add_facility"
    form_class = FacilityCreateForm
    template_name = "facilities/create_facility.html"
    success_url = "/facilities/"

class GenericFacilityUpdateView(AuthorisedFacilityManager, UpdateView):
    permission_required = "facilities.change_facility"
    model = Facility
    form_class = FacilityCreateForm
    template_name = "facilities/update_facility.html"
    success_url = "/facilities/"

class GenericFacilityDetailView(LoginRequiredMixin, DetailView):
    model = Facility
    template_name = "facilities/detail_facility.html"

class GenericFacilityDeleteView(AuthorisedFacilityManager, DeleteView):
    permission_required = "facilities.delete_facility"
    model = Facility
    template_name = "facilities/delete_facility.html"
    success_url = "/facilities/"

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        Facility.objects.filter(pk=self.object.pk).update(deleted=True)
        return HttpResponseRedirect(self.get_success_url())

arike/home/views.py
from django.contrib.auth import forms as auth_forms
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.http import (
    HttpResponse,
    HttpResponseForbidden,
    HttpResponseNotAllowed,
    HttpResponsePermanentRedirect,
)
from arike.users.token import account_activation_token
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView

from arike.home.forms import SetPasswordForm

User = get_user_model()
class UserLoginView(LoginView):
    template_name = 'users/user_login.html'

class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "home/dashboard.html"

class UserProfileWithPasswordChangeView(PasswordChangeView):
    form_class = auth_forms.SetPasswordForm
    template_name = 'home/user_profile.html'
    success_url = '/users'

    def get(self, request, *args, **kwargs):
        user = User.objects.get(pk=kwargs['pk'])
        if self.request.user.id != user.id or user.is_active == False:
            return HttpResponseForbidden("You are not allowed to access this page")

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'] = User.objects.get(pk=self.kwargs['pk'])
        return context

class ActivateAccountView(UpdateView):
    form_class = SetPasswordForm
    template_name = 'home/user_verify_update.html'
    success_url = '/login'

    def get(self, request, *args, **kwargs):
        uidb64 = kwargs['uidb64']
        token = kwargs['token']
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None 
        if user is not None and account_activation_token.check_token(user, token):
            return super().get(request, *args, **kwargs)
        else:
            return HttpResponse("Activation link is invalid!")
    
    def get_object(self):
        uid = force_text(urlsafe_base64_decode(self.kwargs['uidb64']))
        user = User.objects.get(pk=uid)
        return user 
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.object
        return kwargs

    def form_valid(self, form):
        # Set the new password
        password = form.cleaned_data['new_password1']
        self.object.set_password(password)
        self.object.is_verified = True
        self.object.save()

        return HttpResponsePermanentRedirect(self.get_success_url())

arike/templates/treatments/care_sub_type_dropdown.html
<option value="">--------</option>
{% for cst in care_sub_types %} 
    <option value="{{ cst.pk }}">{{ cst.name }}</option>
{% endfor %}

arike/templates/treatments/create_treatment.html
{% extends 'base.html' %}
{% block title %} Add Treatment {% endblock %}

{% block content %}
    {% include 'components/sidenav.html' %}
    <div class="ml-[320px] bg-primary_bg min-h-screen py-8 px-[10%]">
        <h1 class="text-4xl text-primary_color font-extrabold">Add Treatment</h1>
        <form action="" method="post" class="w-full flex flex-row flex-wrap mt-14" data-care_sub_types-url="{% url 'treatments:load_care_sub_types' %}">
            {% csrf_token %}
 
            <select title="Select Care Type" name="{{ form.care_type.html_name }}" id="{{form.care_type.auto_id}}" class="h-14 max-w-[650px] w-full rounded-2xl border-0 pl-5 my-3 mr-10 focus:ring-0">
                <option value="" disabled selected>Select Care Type</option>
                {% for x, y in form.care_type.field.choices %} 
                    <option value="{{ x }}" {% if form.care_type.value == x %} selected {% endif %}>{{ y }}</option>
                {% endfor %}
            </select>
            {% include 'components/errors.html' with errors=form.care_type.errors %} 

            <select title="Select Care Sub-Type" name="{{ form.care_sub_type.html_name }}" id="{{form.care_sub_type.auto_id}}" class="h-14 max-w-[650px] w-full rounded-2xl border-0 pl-5 my-3 mr-10 focus:ring-0">
                <option value="" disabled selected>Select Care Sub Type</option>
            </select>
            {% include 'components/errors.html' with errors=form.care_sub_type.errors %} 
        
            <textarea 
                name="{{ form.description.html_name }}" 
                id="{{ form.description.auto_id }}" 
                placeholder="{{ form.description.label }}"
                class="max-w-[650px] w-full h-32 my-4 py-3 px-5 placeholder:text-sm placeholder:text-grey_light rounded-2xl border-0 focus:ring-0" 
            >{{ form.description.value|default:'' }}</textarea>
        
            {% include 'components/errors.html' with errors=form.description.errors %} 

            {% include 'components/button.html' with btn_type="submit" btn_text="Add" %}
        </form>
    </div>
{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_care_type").change(event => {
        const url = $("form").attr("data-care_sub_types-url");
        const care_type = event.target.value;

        $.ajax({
            url: url,
            data: {
                'care_type': care_type
            },
            success: data => {
                $("#id_care_sub_type").html(data)
            }
        });
    });
    $.proxy()
</script>
{% endblock %}

arike/templates/treatments/delete_disease_history.html
{% extends 'base.html' %} 
{% block title %} Delete Disease History {% endblock %}

{% block content %}
    {% include 'components/sidenav.html' %} 
    <div class="ml-[320px] bg-primary_bg min-h-screen px-[20%] py-8">
        <h1 class="text-primary_color text-3xl font-extrabold">Delete disease history</h1>
        <p class="text-xl text-primary_color font-medium mt-12">Disease History <i>{{ object.disease }}</i> for patient <i>{{ object.patient }}</i> will be deleted</p>
        <p class="text-xl text-primary_color font-medium mt-1">Are you sure ? Action can not be reversed.</p>
        <form action="" method="post" class="flex flex-row mt-10">
            {% csrf_token %}
            <button type="submit" class="w-[200px] h-14 rounded-[12px] bg-primary_color text-[16px] font-semibold text-white tracking-wider">Delete</button>
            <a href="/patients/{{view.kwargs.uid}}/disease/history" class="ml-9 w-[200px] h-14 rounded-[12px] border-2 border-primary_color text-[16px] font-semibold text-primary_color flex flex-row items-center justify-center">Cancel</a>
        </form>
    </div>
{% endblock %}

arike/templates/treatments/delete_treatment.html
{% extends 'base.html' %} 
{% block title %} Delete Treatment {% endblock %}

{% block content %}
    {% include 'components/sidenav.html' %} 
    <div class="ml-[320px] bg-primary_bg min-h-screen px-[20%] py-8">
        <h1 class="text-primary_color text-3xl font-extrabold">Delete Treatment</h1>
        <p class="text-xl text-primary_color font-medium mt-12">Treatment <i>{{ object.care_type }}</i> for patient <i>{{ object.patient }}</i> will be deleted</p>
        <p class="text-xl text-primary_color font-medium mt-1">Are you sure ? Action can not be reversed.</p>
        <form action="" method="post" class="flex flex-row mt-10">
            {% csrf_token %}
            <button type="submit" class="w-[200px] h-14 rounded-[12px] bg-primary_color text-[16px] font-semibold text-white tracking-wider">Delete</button>
            <a href="/patients/{{view.kwargs.uid}}/disease/treatments" class="ml-9 w-[200px] h-14 rounded-[12px] border-2 border-primary_color text-[16px] font-semibold text-primary_color flex flex-row items-center justify-center">Cancel</a>
        </form>
    </div>
{% endblock %}

arike/templates/treatments/treatment_list.html
{% extends 'base.html' %}
{% block title %} Patient Treatment {% endblock %}

{% block content %}
    {% include 'components/sidenav.html' %}
    <div class="ml-[320px] bg-primary_bg min-h-screen px-16">
        {% include 'components/list_header.html' with header='Treatments' url_namespace='treatments:treatment_create' uid=view.kwargs.uid permission=perms.treatments.add_treatment %}
        
        <h2 class="text-2xl font-bold text-primary_color mt-12">{{ patient }}</h2>
        <p class="text-lg text-grey_dark">{{ patient.address }}</p>

        <div class="flex flex-row flex-wrap items-center mt-4 justify-between">
            {% for treatment in treatments %}
            <div class="flex flex-col min-w-[440px] w-[45%] py-5 px-6 bg-white rounded-2xl my-6">
                <h3 class="text-xl font-bold text-primary_color">{{ treatment.care_type }}</h3>
                <h3 class="text-[16px] font-bold text-grey_dark">{{ treatment.care_sub_type }}</h3>
                <p class="text-[15px] text-grey_dark font-bold pr-5">{{ disease.pretty_created_date }}</p>

                <div class="flex flex-row mt-3">
                    <div class="w-1/2">
                        <p class="text-[15px] text-grey_dark font-bold mt-2">Given By</p>
                        <p class="text-[15px] text-primary_color">{{ treatment.given_by.get_full_name }}</p>
                    </div>
                    <div class="w-1/2">
                        <p class="text-[15px] text-grey_dark font-bold mt-2">Last updated</p>
                        <p class="text-[15px] text-primary_color">{{ treatment.pretty_updated_date }}</p>
                    </div>
                </div>

                <p class="text-[15px] text-grey_dark font-bold mt-2">Description</p>
                <p class="text-[15px] text-primary_color">{{ treatment.description }}</p>

                <div class="flex flex-row mt-4">
                    <a href="/patients/{{ view.kwargs.uid }}/disease/treatments/delete/{{ treatment.id }}" class="bg-white text-primary_color border-2 border-primary_color rounded-lg text-sm font-semibold px-7 py-2">Delete</a>
                    <a href="/patients/{{ view.kwargs.uid }}/disease/treatments/update/{{ treatment.id }}" class="ml-3 bg-primary_color text-white border-2 border-primary_color rounded-lg text-sm font-semibold px-7 py-2">Edit</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

arike/templates/treatments/update_treatment.html
{% extends 'base.html' %}
{% block title %} Update Treatment {% endblock %}

{% block content %}
    {% include 'components/sidenav.html' %}
    <div class="ml-[320px] bg-primary_bg min-h-screen py-8 px-[10%]">
        <h1 class="text-4xl text-primary_color font-extrabold">Update Treatment</h1>
        <form action="" method="post" class="w-full flex flex-row flex-wrap mt-14" data-care_sub_types-url="{% url 'treatments:load_care_sub_types' %}">
            {% csrf_token %}
 
            <select title="Select Care Type" name="{{ form.care_type.html_name }}" id="{{form.care_type.auto_id}}" class="h-14 max-w-[650px] w-full rounded-2xl border-0 pl-5 my-3 mr-10 focus:ring-0">
                <option value="" disabled selected>Select Care Type</option>
                {% for x, y in form.care_type.field.choices %} 
                    <option value="{{ x }}" {% if form.care_type.value == x %} selected {% endif %}>{{ y }}</option>
                {% endfor %}
            </select>
            {% include 'components/errors.html' with errors=form.care_type.errors %} 

            <select title="Select Care Sub-Type" name="{{ form.care_sub_type.html_name }}" id="{{form.care_sub_type.auto_id}}" class="h-14 max-w-[650px] w-full rounded-2xl border-0 pl-5 my-3 mr-10 focus:ring-0">
                {% for x, y in form.care_sub_type.field.choices %} 
                    <option value="{{ x }}" {% if form.care_sub_type.value == x %} selected {% endif %}>{{ y }}</option>
                {% endfor %}
            </select>
            {% include 'components/errors.html' with errors=form.care_sub_type.errors %} 
        
            <textarea 
                name="{{ form.description.html_name }}" 
                id="{{ form.description.auto_id }}" 
                placeholder="{{ form.description.label }}"
                class="max-w-[650px] w-full h-32 my-4 py-3 px-5 placeholder:text-sm placeholder:text-grey_light rounded-2xl border-0 focus:ring-0" 
            >{{ form.description.value|default:'' }}</textarea>
        
            {% include 'components/errors.html' with errors=form.description.errors %} 

            {% include 'components/button.html' with btn_type="submit" btn_text="Update" %}
        </form>
    </div>
{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_care_type").change(event => {
        const url = $("form").attr("data-care_sub_types-url");
        const care_type = event.target.value;

        $.ajax({
            url: url,
            data: {
                'care_type': care_type
            },
            success: data => {
                $("#id_care_sub_type").html(data)
            }
        });
    });
    $.proxy()
</script>
{% endblock %}