arike/facilities/urls.py
from django.urls import path

from arike.facilities.views import (
    GenericFacilitiesView,
    GenericFacilityCreateView,
    GenericFacilityDeleteView,
    GenericFacilityDetailView,
    GenericFacilityUpdateView,
)

app_name = "facilities"

urlpatterns = [
    path("", GenericFacilitiesView.as_view(), name="facilities"),
    path("create/", GenericFacilityCreateView.as_view(), name="create_facility"),
    path("detail/<pk>", GenericFacilityDetailView.as_view(), name="facility_detail"),
    path("update/<pk>", GenericFacilityUpdateView.as_view(), name="update_facility"),
    path("delete/<pk>", GenericFacilityDeleteView.as_view(), name="delete_facility"),
]

arike/home/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from arike.home.views import (
    ActivateAccountView,
    DashboardView,
    UserLoginView,
    UserProfileWithPasswordChangeView,
)

app_name = "home"

urlpatterns = [
    path("", DashboardView.as_view(), name="home_dashboard"),
    path("login", UserLoginView.as_view(), name="login_user"),
    path("logout", LogoutView.as_view(), name="logout_user"),
    path("account/<pk>", UserProfileWithPasswordChangeView.as_view(), name="user_profile"),
    path("account/activate/<uidb64>/<token>/", ActivateAccountView.as_view(), name="activate_account"),
]

arike/users/urls.py
from django.urls import path

from arike.users.views import (
    GenericUserAssignView,
    GenericUserCreateView,
    GenericUserDeleteView,
    GenericUserDetailView,
    GenericUserUpdateAssignView,
    GenericUserUpdateView,
    GenericUsersView,
)

app_name = "users"
urlpatterns = [
    path("", GenericUsersView.as_view(), name="users_list"),
    path("create", GenericUserCreateView.as_view(), name="create_user"),
    path("<pk>", GenericUserDetailView.as_view(), name="detail_user"),
    path("update/<pk>", GenericUserUpdateView.as_view(), name="update_user"),
    path("delete/<pk>", GenericUserDeleteView.as_view(), name="delete_user"),
    path("create/<int:uid>/assign", GenericUserAssignView.as_view(), name="assign_facility"),
    path("update/<int:uid>/assign", GenericUserUpdateAssignView.as_view(), name="update_assigned_facility"),
]

arike/visits/urls.py
from django.urls import path

from arike.visits.views import (
    ActiveTreatmentsView,
    CreatePatientHealthInfoView,
    CreateTreatmentNoteView,
    ScheduleVisitView,
    SchedulesView,
    TreatmentDetailView,
    UpcomingVisitsView,
    VisitView,
    unschedule_visit,
)

app_name = "visits"

urlpatterns = [
    path("", SchedulesView.as_view(), name="schedules"),
    path("upcoming", UpcomingVisitsView.as_view(), name="upcoming_visits"),
    path("<int:uid>/schedule", ScheduleVisitView.as_view(), name="schedule_visit"),
    path("<int:uid>/visit/<int:vid>", VisitView.as_view(), name="visit"),
    path("<int:uid>/visit/<int:vid>/delete", unschedule_visit, name="unschedule_visit"),
    path("<int:uid>/visit/<int:vid>/health-info", CreatePatientHealthInfoView.as_view(), name="create_patient_health_info"),
    path("<int:uid>/visit/<int:vid>/treatments", ActiveTreatmentsView.as_view(), name="treatment_note"),
    path("<int:uid>/visit/<int:vid>/treatments/<pk>", TreatmentDetailView.as_view(), name="treatment_details"),
    path("<int:uid>/visit/<int:vid>/treatments/<int:tid>/note", CreateTreatmentNoteView.as_view(), name="create_treatment_note"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path("users/", include("arike.users.urls", namespace="users")),
    path("facilities/", include("arike.facilities.urls", namespace="facilities")),
    path('patients/', include('patients.urls', namespace="patients")),
    path('patients/', include('treatments.urls', namespace='treatments')),
    path('visits/', include('visits.urls', namespace='visits')),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

arike/home/models.py
from django.db import models

class State(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class District(models.Model):
    name = models.CharField(max_length=100)
    state = models.ForeignKey(State, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class LsgBody(models.Model):
    name = models.CharField(max_length=100)
    district = models.ForeignKey(District, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

arike/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from arike.facilities.models import Facility
from arike.home.models import District

ROLE_TYPE = (
    ('none', 'None'),
    ('district_admin', 'District Admin'),
    ('primary_nurse', 'Primary Nurse'),
    ('secondary_nurse', 'Secondary Nurse'),
)

class User(AbstractUser):
    is_verified = models.BooleanField(default=False)
    phone_number = models.CharField(max_length=14, null=True)
    role = models.CharField(max_length=30, choices=ROLE_TYPE, default=ROLE_TYPE[0][0])
    district = models.ForeignKey(District, on_delete=models.CASCADE, null=True)
    facility = models.ForeignKey(Facility, on_delete=models.CASCADE, null=True)

    REQUIRED_FIELDS = ["email", "first_name"]

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username}) 

    def pretty_role(self):
        if self.role == 'none':
            return 'None'
        role = self.role.split('_')  
        role[0] = role[0].title()
        role[1] = role[1].title()
        return ' '.join(role)

arike/facilities/forms.py
from django import forms
from arike.facilities.models import Facility

class FacilityCreateForm(forms.ModelForm):

    class Meta:
        model = Facility
        fields = ['kind', 'name', 'address', 'ward', 'pin_code', 'phone_number']

    def clean_name(self):
        data = self.cleaned_data['name']
        if data is None:
            self.add_error('name', 'Name is required')
        return data 

    def clean_pin_code(self):
        data = self.cleaned_data['pin_code']
        if data is None:
            self.add_error('pin_code', 'Pin code is required')
        return data 
    

arike/facilities/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from arike.facilities.filters import FacilityFilter

from arike.facilities.forms import FacilityCreateForm
from arike.facilities.models import Facility


class AuthorisedFacilityManager(LoginRequiredMixin, PermissionRequiredMixin):

    def get_queryset(self):
        return Facility.objects.filter(deleted=False)
    
class GenericFacilitiesView(LoginRequiredMixin, ListView):
    template_name = "facilities/facilities.html"
    context_object_name = "facilities"

    def get_queryset(self):
        return Facility.objects.filter(deleted=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = FacilityFilter(self.request.GET, queryset=self.get_queryset())
        return context 

class GenericFacilityCreateView(AuthorisedFacilityManager, CreateView):
    permission_required = "facilities.add_facility"
    form_class = FacilityCreateForm
    template_name = "facilities/create_facility.html"
    success_url = "/facilities/"

class GenericFacilityUpdateView(AuthorisedFacilityManager, UpdateView):
    permission_required = "facilities.change_facility"
    model = Facility
    form_class = FacilityCreateForm
    template_name = "facilities/update_facility.html"
    success_url = "/facilities/"

class GenericFacilityDetailView(LoginRequiredMixin, DetailView):
    model = Facility
    template_name = "facilities/detail_facility.html"

class GenericFacilityDeleteView(AuthorisedFacilityManager, DeleteView):
    permission_required = "facilities.delete_facility"
    model = Facility
    template_name = "facilities/delete_facility.html"
    success_url = "/facilities/"

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        Facility.objects.filter(pk=self.object.pk).update(deleted=True)
        return HttpResponseRedirect(self.get_success_url())

arike/home/views.py
from django.contrib.auth import forms as auth_forms
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.http import (
    HttpResponse,
    HttpResponseForbidden,
    HttpResponseNotAllowed,
    HttpResponsePermanentRedirect,
)
from arike.users.token import account_activation_token
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView

from arike.home.forms import SetPasswordForm

User = get_user_model()
class UserLoginView(LoginView):
    template_name = 'users/user_login.html'

class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "home/dashboard.html"

class UserProfileWithPasswordChangeView(PasswordChangeView):
    form_class = auth_forms.SetPasswordForm
    template_name = 'home/user_profile.html'
    success_url = '/users'

    def get(self, request, *args, **kwargs):
        user = User.objects.get(pk=kwargs['pk'])
        if self.request.user.id != user.id or user.is_active == False:
            return HttpResponseForbidden("You are not allowed to access this page")

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'] = User.objects.get(pk=self.kwargs['pk'])
        return context

class ActivateAccountView(UpdateView):
    form_class = SetPasswordForm
    template_name = 'home/user_verify_update.html'
    success_url = '/login'

    def get(self, request, *args, **kwargs):
        uidb64 = kwargs['uidb64']
        token = kwargs['token']
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None 
        if user is not None and account_activation_token.check_token(user, token):
            return super().get(request, *args, **kwargs)
        else:
            return HttpResponse("Activation link is invalid!")
    
    def get_object(self):
        uid = force_text(urlsafe_base64_decode(self.kwargs['uidb64']))
        user = User.objects.get(pk=uid)
        return user 
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.object
        return kwargs

    def form_valid(self, form):
        # Set the new password
        password = form.cleaned_data['new_password1']
        self.object.set_password(password)
        self.object.is_verified = True
        self.object.save()

        return HttpResponsePermanentRedirect(self.get_success_url())

arike/patients/views.py
from datetime import datetime
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from arike.patients.filters import PatientFilter
from arike.patients.forms import PatientCreationForm, PatientFamilyCreationForm

from arike.patients.models import Patient, PatientFamily
from arike.treatments.models import TreatmentNote
from arike.visits.models import VisitDetail, VisitSchedule


class AuthorisedPatientManager(LoginRequiredMixin, PermissionRequiredMixin):
    pass 

class PatientsListView(LoginRequiredMixin, ListView):
    model = Patient
    context_object_name = 'patients'
    template_name = 'patients/patients.html'

    def get_queryset(self):
        return Patient.objects.filter(deleted=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PatientFilter(self.request.GET, queryset=self.get_queryset())
        return context

class PatientCreateView(AuthorisedPatientManager, CreateView):
    permission_required = "patients.add_patient"
    model = Patient
    form_class = PatientCreationForm
    template_name = "patients/create_patient.html"
    success_url = "/patients/"

class PatientUpdateView(AuthorisedPatientManager, UpdateView):
    permission_required = "patients.change_patient"
    model = Patient
    form_class = PatientCreationForm
    template_name = "patients/update_patient.html"
    success_url = "/patients/"

class PatientDetailView(LoginRequiredMixin, DetailView):
    model = Patient
    template_name = "patients/detail_patient.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        curr_date = datetime.now().date()
        visit_scheduels = VisitSchedule.objects.filter(patient=self.object, deleted=False)

        last_visit = visit_scheduels.filter(date__lte=curr_date).order_by('-date').first()
        next_visit = visit_scheduels.filter(date__gt=curr_date).order_by('date').first()
        
        context['last_visit'] = f"{last_visit.date.strftime('%d %b %Y')} @ {last_visit.time.strftime('%I %p')}" if last_visit else "Not visited yet"
        context['next_visit'] = f"{next_visit.date.strftime('%d %b %Y')} @ {next_visit.time.strftime('%I %p')}" if next_visit else "No visit scheduled"
        return context

class PatientFamilyListView(LoginRequiredMixin, ListView):
    model = PatientFamily
    context_object_name = 'patient_families'
    template_name = "patients/patient_family.html"

    def get_queryset(self):
        patient_id = self.kwargs['uid']
        return PatientFamily.objects.filter(patient__id=patient_id, deleted=False)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['patient'] = Patient.objects.get(pk=self.kwargs['uid'])
        return context


class PatientFamilyCreateView(AuthorisedPatientManager, CreateView):
    permission_required = "patients.add_patientfamily"
    model = PatientFamily
    form_class = PatientFamilyCreationForm
    template_name = "patients/create_patient_family.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        patient_id = self.kwargs['uid']
        self.object.patient = Patient.objects.get(pk=patient_id)
        self.object.save()

        return HttpResponseRedirect(f"/patients/{patient_id}/family")

class PatientFamilyUpdateView(AuthorisedPatientManager, UpdateView):
    permission_required = "patients.change_patientfamily"
    model = PatientFamily
    form_class = PatientFamilyCreationForm
    template_name = "patients/update_patient_family.html"
    
    def form_valid(self, form):
        self.object = form.save()
        patient_id = self.kwargs['uid']

        return HttpResponseRedirect(f"/patients/{patient_id}/family")

class PatientFamilyDeleteView(AuthorisedPatientManager, DeleteView):
    permission_required = "patients.delete_patientfamily"
    model = PatientFamily
    template_name = "patients/delete_patient_family.html"
    
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        PatientFamily.objects.filter(pk=self.object.pk).update(deleted=True)
        patient_id = kwargs['uid']

        return HttpResponseRedirect(f"/patients/{patient_id}/family")

class PatientVisitHistoryView(LoginRequiredMixin, ListView):
    model = VisitSchedule
    context_object_name = "visit_histories"
    template_name = "patients/visit_history.html"

    def get_queryset(self):
        patient_id = self.kwargs['uid']
        curr_date = datetime.now().date()
        return VisitSchedule.objects.filter(patient__id=patient_id, deleted=False, date__lt=curr_date)


class PatientVisitHistoryDetailView(LoginRequiredMixin, DetailView):
    template_name = "patients/visit_details.html"
    
    def get_object(self):
        return VisitDetail.objects.get(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['notes'] = TreatmentNote.objects.filter(visit_details__id=self.kwargs['pk'])
        return context 

arike/templates/components/button.html
<div class="w-full mt-6">
    <button 
        type="{{ btn_type }}" 
        class="w-[290px] h-14 rounded-[12px] bg-primary_color text-[16px] font-semibold text-white tracking-wider"
    >
        {{ btn_text }}
    </button>
</div>

arike/templates/components/details_header.html
<div class="w-full py-12 flex flex-row items-center justify-between">
    <h2 class="text-3xl text-primary_color font-extrabold">{{ object_name }}</h2>
    {% if perms.users.add_user or request.user.id == object_id %}
    <div class="flex flex-row items-center">
        <a href="/users/delete/{{ object_id }}" class="mr-1 text-primary_color border-2 border-primary_color rounded-lg text-sm font-semibold px-4 py-2">Delete</a>
        <a href="/users/update/{{ object_id }}" class="ml-1 bg-primary_color text-white border-2 border-primary_color rounded-lg text-sm font-semibold px-6 py-2">Edit</a>
    </div>
    {% endif %}
</div>

arike/templates/components/errors.html
{% if errors %} 
    <ul class="mt-3 list-disc">
        {% for error in errors %} 
            <li class="text-xs text-warning mt-1 last:mb-2">{{ error }}</li>
        {% endfor %}
    </ul>
{% endif %}

arike/templates/components/facility_card.html
<div class="min-w-[400px] w-[45%] flex flex-col items-start justify-between rounded-2xl bg-white py-3 my-4">
    <div class="flex flex-row items-center justify-between w-full px-6">
        <h2 class="text-lg font-bold text-primary_color">{{ facility.name }}</h2>
        <span class="text-sm px-4 py-[2px] rounded-2xl bg-secondary_bg">{{ facility.pretty_kind }}</span>
    </div>
    <div class="w-full px-6">
        <p class="w-3/4 text-sm font-medium text-grey_light my-2">{{ facility.address }}</p>
        <p class="text-[16px] font-bold text-grey_light">{{ facility.ward }}</p>
    </div>
    <p class="w-full h-[2px] bg-secondary_bg my-2"></p>
    <div class="w-full flex flex-row items-center justify-between my-2 px-6">
        <span class="text-primary_color font-bold text-sm">{{ facility.phone_number }}</span>
        <a href="{% url 'facilities:facility_detail' pk=facility.pk %}" class="px-5 border-2 border-primary_color rounded-lg py-1 text-sm text-primary_color font-medium">View</a>
    </div>
</div>

arike/templates/components/input.html
<div class="h-14 w-[320px] inline-block pl-6 py-1 rounded-2xl bg-white my-4 mr-10">
    <label for="{{ field.id_for_label }}" class="block text-sm text-[#6E7191]">{{ field.label }}</label>
    <input 
        type="{{ field.widget_type }}" 
        id="{{ field.auto_id }}" 
        name="{{ field.html_name }}" 
        {% if field.value %} value="{{field.value}}" {% endif %} 
        {% if field.field.required %} required {% endif %}
        placeholder="{{ field.field.widget.attrs.placeholder }}" 
        class="block w-[90%] h-6 leading-5 text-[16px] text-[#14142B] border-0 outline-0 p-0 focus:ring-0"
    >
    <ul class="mt-3 -ml-[0.5rem] list-disc">
        {% for error in field.errors %} 
            <li class="text-xs text-warning mt-1">{{ error }}</li>
        {% endfor %}
    </ul>
</div>

arike/templates/components/link_button.html
<div class="w-full mt-6">
    <a 
        href="{{ url }}" 
        class="flex flex-row items-center justify-center w-[290px] h-14 rounded-[12px] bg-primary_color text-[16px] font-semibold text-white tracking-wider"
    >
        {{ btn_text }}
    </a>
</div>

arike/templates/components/list_header.html
<div class="pt-6">
    <div class="flex flex-row justify-between my-6">
        <h2 class="text-4xl font-extrabold text-primary_color">{{ header }}</h2>
        {% if permission %}
        <a href="{% if uid == '' %}{% url url_namespace %}{% else %}{% url url_namespace uid=uid %}{% endif %}" class="w-24 h-11 text-sm bg-primary_color text-white font-bold rounded-lg flex flex-row items-center justify-center">New</a>
        {% endif %}
    </div>
    <!-- <div class="flex flex-row justify-between my-8">
        <form action="" method="get" class="relative w-[320px] rounded-xl">
            <label for="search" class="absolute p-0 border-0 h-px w-px overflow-hidden">Search facility</label>
            <input 
                type="text"  
                id="search" 
                name="query_param" 
                {% if request.GET.query_param %} value="{{ request.GET.query_param }}" {% endif %}
                placeholder="Search facilities"
                autofocus 
                class="relative w-full h-14 rounded-xl px-4 border-0 outline-0 text-[16px] z-10 focus:ring-0"
            >
            <button type="submit" id="search-btn" class="hidden absolute top-0 right-0 w-16 h-14 border-0 text-lg text-white font-bold rounded-tr-xl rounded-br-xl bg-primary_color tracking-wider">Go</button>
        </form>
        <div class="">
            <input type="text">
            <input type="text">
        </div>
    </div> -->
</div>

arike/templates/components/select_input.html
<div class="w-3/4 mt-4">
    <select name="{{form_field.html_name}}" id="{{form_field.auto_id}}" class="w-full h-14 border-0 rounded-[12px] bg-white pt-[4px] pl-5 focus:ring-0">
        <option value="" disabled selected class="pl-4 text-[#6E7191]">{{ title }}</option>
        {% for x, y in form.fields.district.choices %} 
            <option value="{{ x }}" {% if form_field.value == x %} selected {% endif %}>{{ y }}</option>
        {% endfor %}
    </select>
    
    {% include 'components/errors.html' with errors=form_field.errors %}
</div>

arike/templates/components/sidenav.html
<div class="w-[320px] h-screen px-6 py-8 float-left fixed bg-white">
    <h3 class="text-2xl text-primary_color font-bold">Arike</h3>
    <div class="flex flex-col justify-between h-full">
        <ul class="mt-4 ">
            <li class="mt-2 w-[240px] h-[52px] pl-10 flex flex-row items-center justify-start {% if request.path == '/' %} bg-primary_color text-white rounded-2xl {% else %} text-black font-medium3 {% endif %}"><a href="/" class="text-[16px] w-full py-2">Home</a></li>
            <li class="mt-2 w-[240px] h-[52px] pl-10 flex flex-row items-center justify-start {% if "/facilities/" in request.path %} bg-primary_color text-white rounded-2xl {% else %} text-black font-medium {% endif %}"><a href="/facilities" class="text-[16px] w-full py-2">Facility</a></li>
            <li class="mt-2 w-[240px] h-[52px] pl-10 flex flex-row items-center justify-start {% if "/patients/" in request.path %} bg-primary_color text-white rounded-2xl {% else %} text-black font-medium {% endif %}"><a href="/patients" class="text-[16px] w-full py-2">Patients</a></li>
            <li class="mt-2 w-[240px] h-[52px] pl-10 flex flex-row items-center justify-start {% if "/visits/" in request.path %} bg-primary_color text-white rounded-2xl {% else %} text-black font-medium {% endif %}"><a href="/visits" class="text-[16px] w-full py-2">Schedules</a></li>
            <li class="mt-2 w-[240px] h-[52px] pl-10 flex flex-row items-center justify-start {% if "/users/" in request.path %} bg-primary_color text-white rounded-2xl {% else %} text-black font-medium {% endif %}"><a href="/users" class="text-[16px] w-full py-2">Users</a></li>
            <li class="mt-2 w-[240px] h-[52px] pl-10 flex flex-row items-center justify-start {% if "/account/" in request.path %} bg-primary_color text-white rounded-2xl {% else %} text-black font-medium {% endif %}"><a href="/account/{{ request.user.id }}" class="text-[16px] w-full py-2">Profile</a></li>
        </ul>
    
        <div class="mt-2 mb-8">
            <p class="w-3/4 h-[2px] bg-primary_bg mb-4"></p>
            <div class="flex flex-row items-center justify-start">
                <img class="w-12 h-12 rounded-full ml-1" src="https://images.unsplash.com/photo-1644982647711-9129d2ed7ceb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTgwOTN8MXwxfHNlYXJjaHwxfHxwcm9maWxlfGVufDB8fHx8MTY0NTEyMTE1NQ&ixlib=rb-1.2.1&q=80&w=1080" alt="Profile Picture">
                <div class="flex flex-col justify-between items-center ml-4">
                    <span>{{ request.user.get_full_name }}</span>
                    <a href="/logout" class="text-link_color">Log out</a>
                </div>
            </div>
        </div>

    </div>
</div>

arike/templates/components/user_card.html
<a href="/users/{{ user.id }}" class="flex flex-row items-center w-[45%] rounded-2xl bg-white py-3 my-4">
    <img class="w-14 h-14 rounded-full mx-8" src="https://images.unsplash.com/photo-1644982647711-9129d2ed7ceb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMTgwOTN8MXwxfHNlYXJjaHwxfHxwcm9maWxlfGVufDB8fHx8MTY0NTEyMTE1NQ&ixlib=rb-1.2.1&q=80&w=1080" alt="profile picture">
    <div class="w-full">
        <div class="flex flex-row justify-between w-full">
            <h3 class="text-xl font-bold text-primary_color">{{ user.get_full_name}}</h3>
            <p class="text-xs font-bold text-primary_color px-4 py-[3px] rounded-2xl bg-secondary_bg flex flex-row items-center mr-5">{{ user.get_role_display }}</p>
        </div>
        <p class="text-[16px] font-medium text-primary_color">{{ user.facility }}</p>
        <p class="text-sm font-semibold text-primary_color">{{ user.phone_number|default:'Not provided' }}</p>
        <p class="text-sm font-semibold text-primary_color">{{ user.email }}</p>
    </div>
</a>