arike/home/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from arike.home.views import (
    ActivateAccountView,
    DashboardView,
    UserLoginView,
    UserProfileWithPasswordChangeView,
)

app_name = "home"

urlpatterns = [
    path("", DashboardView.as_view(), name="home_dashboard"),
    path("login", UserLoginView.as_view(), name="login_user"),
    path("logout", LogoutView.as_view(), name="logout_user"),
    path("account/<pk>", UserProfileWithPasswordChangeView.as_view(), name="user_profile"),
    path("account/activate/<uidb64>/<token>/", ActivateAccountView.as_view(), name="activate_account"),
]

arike/users/urls.py
from django.urls import path

from arike.users.views import (
    GenericUserAssignView,
    GenericUserCreateView,
    GenericUserDeleteView,
    GenericUserDetailView,
    GenericUserUpdateAssignView,
    GenericUserUpdateView,
    GenericUsersView,
)

app_name = "users"
urlpatterns = [
    path("", GenericUsersView.as_view(), name="users_list"),
    path("create", GenericUserCreateView.as_view(), name="create_user"),
    path("<pk>", GenericUserDetailView.as_view(), name="detail_user"),
    path("update/<pk>", GenericUserUpdateView.as_view(), name="update_user"),
    path("delete/<pk>", GenericUserDeleteView.as_view(), name="delete_user"),
    path("create/<int:uid>/assign", GenericUserAssignView.as_view(), name="assign_facility"),
    path("update/<int:uid>/assign", GenericUserUpdateAssignView.as_view(), name="update_assigned_facility"),
]

arike/visits/urls.py
from django.urls import path

from arike.visits.views import (
    ActiveTreatmentsView,
    CreatePatientHealthInfoView,
    CreateTreatmentNoteView,
    ScheduleVisitView,
    SchedulesView,
    TreatmentDetailView,
    UpcomingVisitsView,
    VisitView,
    unschedule_visit,
)

app_name = "visits"

urlpatterns = [
    path("", SchedulesView.as_view(), name="schedules"),
    path("upcoming", UpcomingVisitsView.as_view(), name="upcoming_visits"),
    path("<int:uid>/schedule", ScheduleVisitView.as_view(), name="schedule_visit"),
    path("<int:uid>/visit/<int:vid>", VisitView.as_view(), name="visit"),
    path("<int:uid>/visit/<int:vid>/delete", unschedule_visit, name="unschedule_visit"),
    path("<int:uid>/visit/<int:vid>/health-info", CreatePatientHealthInfoView.as_view(), name="create_patient_health_info"),
    path("<int:uid>/visit/<int:vid>/treatments", ActiveTreatmentsView.as_view(), name="treatment_note"),
    path("<int:uid>/visit/<int:vid>/treatments/<pk>", TreatmentDetailView.as_view(), name="treatment_details"),
    path("<int:uid>/visit/<int:vid>/treatments/<int:tid>/note", CreateTreatmentNoteView.as_view(), name="create_treatment_note"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path("users/", include("arike.users.urls", namespace="users")),
    path("facilities/", include("arike.facilities.urls", namespace="facilities")),
    path('patients/', include('patients.urls', namespace="patients")),
    path('patients/', include('treatments.urls', namespace='treatments')),
    path('visits/', include('visits.urls', namespace='visits')),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

arike/treatments/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth import get_user_model
from arike.patients.models import Patient
from arike.visits.models import User, VisitDetail

User = get_user_model()

class Disease(models.Model):
    name = models.CharField(max_length=100)
    icds_code = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name 

class CareType(models.Model):
    name = models.CharField(max_length=100) 

    def __str__(self):
        return self.name

class CareSubType(models.Model):
    name = models.CharField(max_length=200)
    care_type = models.ForeignKey(CareType, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Treatment(models.Model):
    care_type = models.ForeignKey(CareType, on_delete=models.CASCADE)
    care_sub_type = models.ForeignKey(CareSubType, on_delete=models.CASCADE)
    description = models.CharField(max_length=300)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    given_by = models.ForeignKey(User, on_delete=models.CASCADE)
    deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def pretty_created_date(self):
        return self.created_at.strftime("%d %b %Y")
    
    def pretty_updated_date(self):
        return self.updated_at.strftime("%d %b %Y")

class TreatmentNote(models.Model):
    note = models.CharField(max_length=200)
    description = models.CharField(max_length=300, null=True, blank=True)
    treatment = models.ForeignKey(Treatment, on_delete=models.CASCADE)
    visit_details = models.ForeignKey(VisitDetail, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.note

    def pretty_created_date(self):
        return self.created_at.strftime("%d %b %Y")

class PatientDisease(models.Model):
    remarks = models.CharField(max_length=200, blank=True)
    disease = models.ForeignKey(Disease, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    treatment = models.ForeignKey(Treatment, on_delete=models.CASCADE, blank=True, null=True)
    investigated_by = models.ForeignKey(User, on_delete=models.CASCADE)
    deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def pretty_updated(self):
        return self.updated_at.strftime("%d %b %Y")

arike/facilities/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from arike.facilities.filters import FacilityFilter

from arike.facilities.forms import FacilityCreateForm
from arike.facilities.models import Facility


class AuthorisedFacilityManager(LoginRequiredMixin, PermissionRequiredMixin):

    def get_queryset(self):
        return Facility.objects.filter(deleted=False)
    
class GenericFacilitiesView(LoginRequiredMixin, ListView):
    template_name = "facilities/facilities.html"
    context_object_name = "facilities"

    def get_queryset(self):
        return Facility.objects.filter(deleted=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = FacilityFilter(self.request.GET, queryset=self.get_queryset())
        return context 

class GenericFacilityCreateView(AuthorisedFacilityManager, CreateView):
    permission_required = "facilities.add_facility"
    form_class = FacilityCreateForm
    template_name = "facilities/create_facility.html"
    success_url = "/facilities/"

class GenericFacilityUpdateView(AuthorisedFacilityManager, UpdateView):
    permission_required = "facilities.change_facility"
    model = Facility
    form_class = FacilityCreateForm
    template_name = "facilities/update_facility.html"
    success_url = "/facilities/"

class GenericFacilityDetailView(LoginRequiredMixin, DetailView):
    model = Facility
    template_name = "facilities/detail_facility.html"

class GenericFacilityDeleteView(AuthorisedFacilityManager, DeleteView):
    permission_required = "facilities.delete_facility"
    model = Facility
    template_name = "facilities/delete_facility.html"
    success_url = "/facilities/"

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        Facility.objects.filter(pk=self.object.pk).update(deleted=True)
        return HttpResponseRedirect(self.get_success_url())

arike/home/views.py
from django.contrib.auth import forms as auth_forms
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.http import (
    HttpResponse,
    HttpResponseForbidden,
    HttpResponseNotAllowed,
    HttpResponsePermanentRedirect,
)
from arike.users.token import account_activation_token
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView

from arike.home.forms import SetPasswordForm

User = get_user_model()
class UserLoginView(LoginView):
    template_name = 'users/user_login.html'

class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "home/dashboard.html"

class UserProfileWithPasswordChangeView(PasswordChangeView):
    form_class = auth_forms.SetPasswordForm
    template_name = 'home/user_profile.html'
    success_url = '/users'

    def get(self, request, *args, **kwargs):
        user = User.objects.get(pk=kwargs['pk'])
        if self.request.user.id != user.id or user.is_active == False:
            return HttpResponseForbidden("You are not allowed to access this page")

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'] = User.objects.get(pk=self.kwargs['pk'])
        return context

class ActivateAccountView(UpdateView):
    form_class = SetPasswordForm
    template_name = 'home/user_verify_update.html'
    success_url = '/login'

    def get(self, request, *args, **kwargs):
        uidb64 = kwargs['uidb64']
        token = kwargs['token']
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None 
        if user is not None and account_activation_token.check_token(user, token):
            return super().get(request, *args, **kwargs)
        else:
            return HttpResponse("Activation link is invalid!")
    
    def get_object(self):
        uid = force_text(urlsafe_base64_decode(self.kwargs['uidb64']))
        user = User.objects.get(pk=uid)
        return user 
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.object
        return kwargs

    def form_valid(self, form):
        # Set the new password
        password = form.cleaned_data['new_password1']
        self.object.set_password(password)
        self.object.is_verified = True
        self.object.save()

        return HttpResponsePermanentRedirect(self.get_success_url())

arike/patients/views.py
from datetime import datetime
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from arike.patients.filters import PatientFilter
from arike.patients.forms import PatientCreationForm, PatientFamilyCreationForm

from arike.patients.models import Patient, PatientFamily
from arike.treatments.models import TreatmentNote
from arike.visits.models import VisitDetail, VisitSchedule


class AuthorisedPatientManager(LoginRequiredMixin, PermissionRequiredMixin):
    pass 

class PatientsListView(LoginRequiredMixin, ListView):
    model = Patient
    context_object_name = 'patients'
    template_name = 'patients/patients.html'

    def get_queryset(self):
        return Patient.objects.filter(deleted=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PatientFilter(self.request.GET, queryset=self.get_queryset())
        return context

class PatientCreateView(AuthorisedPatientManager, CreateView):
    permission_required = "patients.add_patient"
    model = Patient
    form_class = PatientCreationForm
    template_name = "patients/create_patient.html"
    success_url = "/patients/"

class PatientUpdateView(AuthorisedPatientManager, UpdateView):
    permission_required = "patients.change_patient"
    model = Patient
    form_class = PatientCreationForm
    template_name = "patients/update_patient.html"
    success_url = "/patients/"

class PatientDetailView(LoginRequiredMixin, DetailView):
    model = Patient
    template_name = "patients/detail_patient.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        curr_date = datetime.now().date()
        visit_scheduels = VisitSchedule.objects.filter(patient=self.object, deleted=False)

        last_visit = visit_scheduels.filter(date__lte=curr_date).order_by('-date').first()
        next_visit = visit_scheduels.filter(date__gt=curr_date).order_by('date').first()
        
        context['last_visit'] = f"{last_visit.date.strftime('%d %b %Y')} @ {last_visit.time.strftime('%I %p')}" if last_visit else "Not visited yet"
        context['next_visit'] = f"{next_visit.date.strftime('%d %b %Y')} @ {next_visit.time.strftime('%I %p')}" if next_visit else "No visit scheduled"
        return context

class PatientFamilyListView(LoginRequiredMixin, ListView):
    model = PatientFamily
    context_object_name = 'patient_families'
    template_name = "patients/patient_family.html"

    def get_queryset(self):
        patient_id = self.kwargs['uid']
        return PatientFamily.objects.filter(patient__id=patient_id, deleted=False)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['patient'] = Patient.objects.get(pk=self.kwargs['uid'])
        return context


class PatientFamilyCreateView(AuthorisedPatientManager, CreateView):
    permission_required = "patients.add_patientfamily"
    model = PatientFamily
    form_class = PatientFamilyCreationForm
    template_name = "patients/create_patient_family.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        patient_id = self.kwargs['uid']
        self.object.patient = Patient.objects.get(pk=patient_id)
        self.object.save()

        return HttpResponseRedirect(f"/patients/{patient_id}/family")

class PatientFamilyUpdateView(AuthorisedPatientManager, UpdateView):
    permission_required = "patients.change_patientfamily"
    model = PatientFamily
    form_class = PatientFamilyCreationForm
    template_name = "patients/update_patient_family.html"
    
    def form_valid(self, form):
        self.object = form.save()
        patient_id = self.kwargs['uid']

        return HttpResponseRedirect(f"/patients/{patient_id}/family")

class PatientFamilyDeleteView(AuthorisedPatientManager, DeleteView):
    permission_required = "patients.delete_patientfamily"
    model = PatientFamily
    template_name = "patients/delete_patient_family.html"
    
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        PatientFamily.objects.filter(pk=self.object.pk).update(deleted=True)
        patient_id = kwargs['uid']

        return HttpResponseRedirect(f"/patients/{patient_id}/family")

class PatientVisitHistoryView(LoginRequiredMixin, ListView):
    model = VisitSchedule
    context_object_name = "visit_histories"
    template_name = "patients/visit_history.html"

    def get_queryset(self):
        patient_id = self.kwargs['uid']
        curr_date = datetime.now().date()
        return VisitSchedule.objects.filter(patient__id=patient_id, deleted=False, date__lt=curr_date)


class PatientVisitHistoryDetailView(LoginRequiredMixin, DetailView):
    template_name = "patients/visit_details.html"
    
    def get_object(self):
        return VisitDetail.objects.get(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['notes'] = TreatmentNote.objects.filter(visit_details__id=self.kwargs['pk'])
        return context 

arike/templates/visits/active_treatments.html
{% extends 'base.html' %}
{% block title %} Patient Treatment {% endblock %}

{% block content %}
    {% include 'components/sidenav.html' %}
    <div class="ml-[320px] bg-primary_bg min-h-screen px-[10%]">
        {% include 'components/list_header.html' with header='Active Treatments' url_namespace='treatments:treatment_create' uid=view.kwargs.uid permission=perms.treatments.add_treatment %}
        
        <h2 class="text-2xl font-bold text-primary_color mt-12">{{ patient }}</h2>
        <p class="text-lg text-grey_dark">{{ patient.address }}</p>

        <div class="flex flex-row flex-wrap items-center mt-4 justify-between">
            {% for treatment in treatments %}
            <div class="flex flex-col w-full py-6 px-8 bg-white rounded-2xl my-7 cursor-pointer treatment_cont" data-treatment_details_url="{% url 'visits:treatment_details' uid=view.kwargs.uid vid=view.kwargs.vid pk=treatment.pk %}">
                <div class="flex flex-row justify-between">
                    <h3 class="text-xl font-bold text-primary_color">{{ treatment.care_type }}</h3>
                    <a href="{% url 'visits:create_treatment_note' uid=view.kwargs.uid vid=view.kwargs.vid tid=treatment.pk %}" class="ml-3 bg-primary_color text-white border-2 border-primary_color rounded-lg text-sm font-semibold px-7 py-2">Add Note</a>
                </div>
                <h3 class="text-[16px] font-bold text-grey_dark">{{ treatment.care_sub_type }}</h3>

                <div class="flex flex-row mt-3">
                    <div class="w-1/2">
                        <p class="text-[15px] text-grey_dark font-bold mt-2">Given By</p>
                        <p class="text-[15px] text-primary_color">{{ treatment.given_by.get_full_name }}</p>
                    </div>
                    <div class="w-1/2">
                        <p class="text-[15px] text-grey_dark font-bold mt-2">Last updated</p>
                        <p class="text-[15px] text-primary_color">{{ treatment.pretty_updated_date }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function() {
        $('.treatment_cont').click(function() {
            window.location.href = $(this).data('treatment_details_url');
        });
    });
</script>
 {% endblock %}

arike/templates/visits/create_treatment_note.html
{% extends 'base.html' %}
{% block title %} Patient Treatment {% endblock %}

{% block content %}
    {% include 'components/sidenav.html' %}
    <div class="ml-[320px] bg-primary_bg min-h-screen px-[10%] pt-12">
        <h2 class="text-3xl font-extrabold text-primary_color mt-8">Add Notes</h2>

        <div class="flex flex-col w-full py-6 px-8 bg-white rounded-2xl mt-8">
            <h3 class="text-xl font-bold text-primary_color">{{ treatment.care_type }}</h3>
            <h3 class="text-[15px] font-medium text-grey_dark">{{ treatment.care_sub_type }}</h3>

            <div class="flex flex-row mt-3">
                <div class="w-1/2">
                    <p class="text-[15px] text-grey_dark font-bold mt-2">Given By</p>
                    <p class="text-[15px] text-primary_color">{{ treatment.given_by.get_full_name }}</p>
                </div>
                <div class="w-1/2">
                    <p class="text-[15px] text-grey_dark font-bold mt-2">Last updated</p>
                    <p class="text-[15px] text-primary_color">{{ treatment.pretty_updated_date }}</p>
                </div>
            </div>
        </div>

        <form action="" method="post">
            {% csrf_token %}
            <textarea 
                name="{{ form.note.html_name }}" 
                id="{{ form.note.auto_id }}" 
                required
                placeholder="Note"
                class="w-full h-48 mt-8 py-3 px-5 placeholder:text-[16px] placeholder:text-grey_light rounded-2xl border-0 focus:ring-0" 
            ></textarea>
            
            {% include 'components/button.html' with btn_type='submit' btn_text='Add' %}
        </form>

    </div>
{% endblock %}

arike/templates/visits/schedules.html
{% extends 'base.html' %}
{% block title %} Schedules {% endblock %}

{% block content %}
    {% include 'components/sidenav.html' %}
    <div class="ml-[320px] bg-primary_bg min-h-screen px-16">
        <div class="flex flex-row justify-between py-6">
            <h2 class="text-4xl font-extrabold text-primary_color">Schedule</h2>
                <a href="{% url 'visits:upcoming_visits' %}" class="h-11 px-6 text-sm bg-primary_color text-white font-bold rounded-lg flex flex-row items-center justify-center">Upcoming Visits</a>
        </div>

        <div class="flex flex-row flex-wrap items-center mt-4 justify-between">
            {% for disease in patient_diseases %}
            <a href="{% url 'visits:schedule_visit' uid=disease.patient.id %}" class="flex flex-col min-w-[300px] w-[30%] py-5 px-6 bg-white rounded-2xl my-6">
                <div class="flex flex-row justify-between">
                    <h3 class="text-xl font-bold text-primary_color">{{ disease.patient }}</h3>
                    <span class="text-[15px] text-grey_dark font-semibold pr-5">{{ disease.patient.ward }}</span>
                </div>
                <p class="mt-2 text-[15px] text-grey_dark font-semibold">{{ disease.disease }}</p>
                <p class="text-[15px] text-grey_dark font-semibold">{{ disease.treatment.care_type }}</p>
                <p class="text-[15px] text-grey_dark font-semibold">{{ disease.treatment.care_sub_type }}</p>
            </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

arike/templates/visits/upcoming_visits.html
{% extends 'base.html' %}
{% block title %} Visits {% endblock %}

{% block content %}
    {% include 'components/sidenav.html' %}
    <div class="ml-[320px] bg-primary_bg min-h-screen px-[5%] pt-12" id="wrapper">
        <h2 class="text-4xl font-extrabold text-primary_color">Pending Visits</h2>
        <h3 class="text-2xl font-bold text-primary_color mt-12">Today <span class="text-grey_dark">{{ today|length }} visits</span></h3>
        <div class="flex flex-row flex-wrap">
            {% for item in today %}
            <div class="min-w-[300px] w-[30%] bg-white rounded-2xl px-6 py-5 mr-10 mt-6">
                <h3 class="text-xl font-bold text-primary_color">{{ item.patient }}</h3>
                <p class="text-[15px] text-grey_dark">{{ item.patient.address }}</p>
                <p class="mt-2 text-[15px] text-primary_color">{{ item.patient.age }} years old</p>
                <p class="mt-1 text-[15px] text-link_color font-semibold">{{ item.patient.phone_number }}</p>
                <div class="flex flex-row mt-4">
                    <button type="button" data-unschedule-url="{% url 'visits:unschedule_visit' uid=item.patient.pk vid=item.pk %}" class="bg-white text-primary_color border-2 border-primary_color rounded-lg text-sm font-semibold px-7 py-2">Unschedule</button>
                    <a href="/visits/{{ item.patient.pk }}/visit/{{ item.id }}" class="ml-3 bg-primary_color text-white border-2 border-primary_color rounded-lg text-sm font-semibold px-7 py-2">Visit</a>
                </div>
            </div>
            {% endfor %}
        </div>
        <h3 class="text-2xl font-bold text-primary_color mt-12 w-full">Tomorrow <span class="text-grey_dark">{{ tomorrow|length }} visits</span></h3>
        <div class="flex flex-row flex-wrap">
            {% for item in tomorrow %}
            <div class="min-w-[300px] w-[30%] bg-white rounded-2xl px-6 py-5 mr-10 mt-6">
                <h3 class="text-xl font-bold text-primary_color">{{ item.patient }}</h3>
                <p class="text-[15px] text-grey_dark">{{ item.patient.address }}</p>
                <p class="mt-2 text-[15px] text-primary_color">{{ item.patient.age }} years old</p>
                <p class="mt-1 text-[15px] text-link_color font-semibold">{{ item.patient.phone_number }}</p>
                <div class="flex flex-row mt-4">
                    <button type="button" data-unschedule_url="{% url 'visits:unschedule_visit' uid=item.patient.pk vid=item.pk %}" class="bg-white text-primary_color border-2 border-primary_color rounded-lg text-sm font-semibold px-7 py-2">Unschedule</button>
                    <a href="/visits/{{ item.patient.pk }}/visit/{{ item.id }}" class="ml-3 bg-primary_color text-white border-2 border-primary_color rounded-lg text-sm font-semibold px-7 py-2">Visit</a>
                </div>
            </div>
            {% endfor %}

        <h3 class="text-2xl font-bold text-primary_color mt-12 w-full">Next Week <span class="text-grey_dark">{{ next_week|length }} visits</span></h3>
        <div class="flex flex-row flex-wrap">
            {% for item in next_week %}
            <div class="min-w-[300px] w-[30%] bg-white rounded-2xl px-6 py-5 mr-10 mt-6">
                <h3 class="text-xl font-bold text-primary_color">{{ item.patient }}</h3>
                <p class="text-[15px] text-grey_dark">{{ item.patient.address }}</p>
                <p class="mt-2 text-[15px] text-primary_color">{{ item.patient.age }} years old</p>
                <p class="mt-1 text-[15px] text-link_color font-semibold">{{ item.patient.phone_number }}</p>
                <div class="flex flex-row mt-4">
                    <button type="button" data-unschedule-url="{% url 'visits:unschedule_visit' uid=item.patient.pk vid=item.pk %}" class="bg-white text-primary_color border-2 border-primary_color rounded-lg text-sm font-semibold px-7 py-2">Unschedule</button>
                    <a href="/visits/{{ item.patient.pk }}/visit/{{ item.id }}" class="ml-3 bg-primary_color text-white border-2 border-primary_color rounded-lg text-sm font-semibold px-7 py-2">Visit</a>
                </div>
            </div>
            {% endfor %}
    </div>
{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    const wrapper = document.getElementById('wrapper');
    wrapper.addEventListener('click', event => {
        const isButton = event.target.nodeName === 'BUTTON';
        if (!isButton) {
            return;
        }

        const url = event.target.dataset.unschedule_url
        $.ajax({
            url: url,
            success: data => {
                window.location.reload();
            }
        })
    })
    $.proxy()
</script>
{% endblock %}

arike/templates/visits/visit.html
{% extends 'base.html' %}
{% block title %} Visit {% endblock %}

{% block content %}
    {% include 'components/sidenav.html' %}
    <div class="ml-[320px] bg-primary_bg min-h-screen px-[5%] pt-12">
        <h2 class="text-3xl font-extrabold text-primary_color">Visit</h2>
        <div class="w-full mt-12 flex flex-row flex-wrap justify-between">
            <a href="{% url 'visits:treatment_note' uid=view.kwargs.uid vid=view.kwargs.vid %}" class="min-w-[360px] w-2/5 h-[190px] bg-white rounded-2xl flex flex-row items-center justify-center text-2xl text-primary_color font-extrabold">Treatment Notes</a>
            <a href="{% url 'visits:create_patient_health_info' uid=view.kwargs.uid vid=view.kwargs.vid %}" class="min-w-[360px] w-2/5 h-[190px] bg-white rounded-2xl flex flex-row items-center justify-center text-2xl text-primary_color font-extrabold">Health Information</a>
        </div>
    </div>
{% endblock %}